- name: Leave Swarm
  ansible.builtin.shell:
    cmd: docker swarm leave --force
  when: state.stdout != 'inactive'

- name: Join Swarm as worker
  ansible.builtin.shell:
    cmd: docker swarm join --token {{ token }} {{ hostvars[groups['mgmt'][0]]['ansible_default_ipv4']['address'] }}:2377
