- name: Setup Docker
  hosts: node
  become: true
  roles:
    - role: node

- name: Setup Swarm
  hosts: mgmt[0]
  roles:
    - role: mgmt
      vars:
        origin: true

- name: Setup Manager
  hosts: mgmt:!mgmt[0]
  roles:
    - role: mgmt
      vars:
        origin: false
        token: "{{ hostvars[groups['mgmt'][0]]['mtok'].stdout }}"

- name: Setup Worker
  hosts: work
  roles:
    - role: work
      vars:
        token: "{{ hostvars[groups['mgmt'][0]]['wtok'].stdout }}"

- name: Deploy registry
  hosts: zeus
  tasks:
    - name: Start or Create
      ansible.builtin.shell:
        cmd: docker start registry || docker run -d -p 5000:5000 --restart always --name registry registry:latest
